// <auto-generated />
using System;
using CloudOrders.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudOrders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CloudOrdersDbContext))]
    [Migration("20260816221235_InitialSqlPersistence")]
    partial class InitialSqlPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudOrders.Infrastructure.Persistence.IdempotencyRecordEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "IdempotencyKey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_IdempotencyRecords_ExpiresAt");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_IdempotencyRecords_OrderId");

                    b.ToTable("IdempotencyRecords", "dbo");
                });

            modelBuilder.Entity("CloudOrders.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CustomerReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerReference", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Orders_CustomerReference_CreatedAt_Id");

                    b.ToTable("Orders", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Quantity", "[Quantity] >= 1 AND [Quantity] <= 100");

                            t.HasCheckConstraint("CK_Orders_Status", "[Status] IN (N'Pending', N'Processing')");
                        });
                });

            modelBuilder.Entity("CloudOrders.Infrastructure.Persistence.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("MessageVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("EventId");

                    b.HasIndex("OrderId");

                    b.HasIndex("CreatedAt", "EventId")
                        .HasDatabaseName("IX_OutboxMessages_Pending")
                        .HasFilter("[ProcessedAt] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedAt", "EventId"), new[] { "MessageType", "MessageVersion", "OccurredAt", "AttemptCount" });

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("CloudOrders.Infrastructure.Persistence.IdempotencyRecordEntity", b =>
                {
                    b.HasOne("CloudOrders.Infrastructure.Persistence.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CloudOrders.Infrastructure.Persistence.OutboxMessageEntity", b =>
                {
                    b.HasOne("CloudOrders.Infrastructure.Persistence.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
